services:
  potato-identifier-dev:
    container_name: potato-identifier-dev
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        APP_ROOT: /app
        IMAGE_ARCH: amd64
    image: kassiell/potato-identifier:dev
    privileged: true
    network_mode: "host"
    environment:
      - "DISPLAY=:99"
      - "QT_QPA_PLATFORM=offscreen"
    volumes:
      - "./src:/app/src:rw"  # Mount source for live development
      - "./data:/app/data:ro"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "
      . /app/.venv/bin/activate &&
      python3 -u src/check_npu.py &&
      python3 -u src/main.py --no-sandbox
      "
