#!/bin/bash
# Script para facilitar configuração da câmera USB no WSL2

echo "=== CONFIGURAÇÃO CÂMERA USB NO WSL2 ==="
echo ""
echo "INFORMAÇÕES DA SUA CÂMERA:"
echo "USB\\VID_32E4&PID_9230 - Driver: usbvideo.inf"
echo "Tipo: Câmera USB comum (UVC - USB Video Class)"
echo ""
echo "PASSO 1: INSTALAR USBIPD NO WINDOWS"
echo "Execute no PowerShell como Administrador:"
echo "winget install --interactive --exact dorssel.usbipd-win"
echo ""
echo "PASSO 2: REINICIAR O WINDOWS"
echo ""
echo "PASSO 3: IDENTIFICAR A CÂMERA"
echo "Execute no PowerShell como Administrador:"
echo "usbipd list"
echo ""
echo "Procure por um dispositivo como:"
echo "BUSID  VID:PID    DEVICE                                                        STATE"
echo "X-Y    32e4:9230  USB Video Device, USB Camera                                 Not shared"
echo ""
echo "PASSO 4: COMPARTILHAR A CÂMERA"
echo "Execute no PowerShell como Administrador:"
echo "usbipd bind --busid X-Y  # Substitua X-Y pelo BUSID da sua câmera"
echo "usbipd attach --wsl --busid X-Y"
echo ""
echo "PASSO 5: VERIFICAR NO WSL2"
echo "Execute no terminal WSL2:"
echo "cd /home/cristiano/potato-Identifier"
echo "./scripts/dev.sh test-usb     # Teste específico para câmeras USB"
echo "./scripts/dev.sh test-camera  # Teste geral da aplicação"
echo ""
echo "=== COMANDOS DE REFERÊNCIA ==="
echo ""
echo "WINDOWS (PowerShell como Admin):"
echo "  usbipd list                    # Listar dispositivos"
echo "  usbipd state                   # Ver status"
echo "  usbipd detach --busid X-Y      # Desconectar do WSL2"
echo "  usbipd attach --wsl --busid X-Y # Reconectar ao WSL2"
echo ""
echo "WSL2:"
echo "  lsusb                          # Ver dispositivos USB"
echo "  ls /dev/video*                 # Ver dispositivos de vídeo"
echo "  ./scripts/dev.sh test-usb      # Testar câmeras USB"
echo "  ./scripts/dev.sh run           # Executar aplicação"
echo ""
echo "=== SOLUÇÃO DE PROBLEMAS ==="
echo ""
echo "Se a câmera não aparecer:"
echo "1. Verifique se está fisicamente conectada ao USB"
echo "2. Execute 'usbipd list' no Windows para confirmar detecção"
echo "3. Certifique-se de fazer 'bind' antes de 'attach'"
echo "4. Reinicie o WSL2: 'wsl --shutdown' e reabra"
echo "5. Verifique permissões: sudo usermod -a -G video \$USER"
echo ""
echo "=== VANTAGENS DA CÂMERA USB ==="
echo ""
echo "✅ Mais simples que câmeras Basler"
echo "✅ Não precisa do PyPylon"
echo "✅ Suporte nativo do OpenCV"
echo "✅ Plug and play após configurar usbipd"
echo ""
echo "Para mais detalhes, consulte: SETUP_CAMERA_WSL2.md"
